[[language]]
name = "toml"
scope = "source.toml"
injection-regex = "toml"
file-types = ["toml", "poetry.lock", "Cargo.lock"]
roots = []
comment-token = "#"
# TODO: uncomment after merging https://github.com/tamasfe/taplo/pull/354
# language-server = { command= "taplo", args = ["lsp", "stdio"] }
language-server = { command = "" }
indent = { tab-width = 2, unit = "  " }
auto-format = false
