live_config_reload = true

[shell]
program = "/usr/local/bin/fish"

[env]
TERM = "xterm-256color"


[font]
size = 18.0
normal = { family = "JetBrains Mono NL", style = "Regular" }
bold = { family = "JetBrains Mono NL", style = "Bold" }
italic = { family = "JetBrains Mono NL", style = "Italic" }
bold_italic = { family = "JetBrains Mono NL", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[window]
decorations = "none"
startup_mode = "Maximized"
padding = { x = 10, y = 10 }

[scrolling]
history = 10000
multiplier = 3


[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true


[terminal]
osc52 = "CopyPaste"
