theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = true
cursorline = true
auto-save = true
bufferline = "multiple"
auto-pairs = true
completion-trigger-len = 2
shell = ["zsh", "-c"]
color-modes = true
idle-timeout = 0


[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = [
  "mode",
  # "spacer",
  "spinner",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator",
]
right = [
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25          # increase value to reduce forced mid-word wrapping
max-indent-retain = 40

[keys.select]
esc = ["normal_mode", "collapse_selection", "keep_primary_selection", ":w"]
y = "yank_joined_to_clipboard"
